FROM node:14-alpine As development

WORKDIR /usr/src/app

COPY ./server/package*.json ./server

RUN npm install --only=development

COPY ./server .

RUN npm run build

FROM node:14-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./server/package*.json ./server

RUN npm install --only=production

COPY ./server .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]