FROM node:14-alpine As development

WORKDIR /usr/src/app

COPY ./server/package*.json ./

RUN yarn install --production=false

COPY ./server .

RUN yarn add -g glob rimraf

RUN yarn build

FROM node:14-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY ./server/package*.json ./

RUN yarn install --production

COPY ./server .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]